a = str(input("Enter Your 1st name :"))
b = str(input("Enter Your 2nd name :"))
print(f"strln =",len(a))
print(a)
print(a.strip())
print(a.upper())
x = a.lower()
print(x.strip())
print(a.split())
c = input("Enter Change 2nd name :")
print(a," ",b.replace(b, c))
print(b.split())
